apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: nodejs  # The namespace should be defined at this level for the entire Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: node
          image: archanasingh05/nodejs-app  # Make sure this is the correct image path
          ports:
            - containerPort: 5000
